# Useful Functions
source "$ZDOTDIR/zsh-functions"

# Normale files to source
zsh_add_file "aliases"

# Plugins
zsh_add_plugin "zsh-users/zsh-autosuggestions"
zsh_add_plugin "zsh-users/zsh-syntax-highlighting"
